# Generated by Django 5.1.1 on 2024-09-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('revenu', models.FloatField()),
                ('age', models.IntegerField()),
                ('revenue_codebiteur', models.FloatField(blank=True, null=True)),
                ('age_codebiteur', models.IntegerField(blank=True, null=True)),
                ('type_credit', models.CharField(choices=[('véhicules particuliers de tourisme', 'véhicules particuliers de tourisme'), ('cycles et tricycles à moteur', 'cycles et tricycles à moteur'), ("informatique, téléphonie, electroménager, téléviseurs, meubles, accessoires en bois, tissues d'ameublement", "informatique, téléphonie, electroménager, téléviseurs, meubles, accessoires en bois, tissues d'ameublement")], max_length=1000)),
                ('frequence', models.CharField(choices=[('Mensuel', 'Mensuel'), ('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel'), ('Annuel', 'Annuel')], max_length=1000)),
                ('duree', models.IntegerField()),
            ],
        ),
    ]
