# Generated by Django 5.1.1 on 2024-09-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='revenu',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
