# Generated by Django 5.1.1 on 2024-09-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_revenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hamish_jiddiya',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='revenu',
            field=models.FloatField(default=2000),
        ),
    ]
