# Generated by Django 5.1.1 on 2024-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_client_hamish_jiddiya_alter_client_revenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='revenu',
            field=models.FloatField(),
        ),
    ]
