# Generated by Django 5.1.1 on 2024-09-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_userprofile_user_client_credit_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit',
            field=models.FloatField(),
        ),
    ]
